In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2024-08-21 16:34:34.341160: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-08-21 16:34:34.435620: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-08-21 16:34:34.547607: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-21 16:34:34.635331: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-21 16:34:34.657643: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-21 16:34:34.788744: I tensorflow/core/platform/cpu_feature_gu

In [3]:
sent = {
    "the glass of milk",
    "the glass of juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "understand the meaning of words",
    "your videos are good"
}

In [4]:
sent

{'I am a good boy',
 'I am a good developer',
 'the cup of tea',
 'the glass of juice',
 'the glass of milk',
 'understand the meaning of words',
 'your videos are good'}

In [5]:
voc_size = 10000

In [6]:
one_hot_repr = [one_hot(words,voc_size) for words in sent]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4174 7977 1206 1629]
 [   0    0    0    0 4174 4240 1206 3760]
 [   0    0    0    0 4174 4240 1206  839]
 [   0    0    0 1096 5502 7725 2493 7187]
 [   0    0    0 2427 4174 9290 1206 6404]
 [   0    0    0 1096 5502 7725 2493 4821]
 [   0    0    0    0 8420 8701 9081 2493]]


In [11]:
dim = 10

In [13]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/home/ayush/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step


array([[[-0.03260424,  0.02628894, -0.00715079,  0.02018868,
          0.01542927, -0.00427831, -0.04009442,  0.0421882 ,
          0.02576596,  0.04819346],
        [-0.03260424,  0.02628894, -0.00715079,  0.02018868,
          0.01542927, -0.00427831, -0.04009442,  0.0421882 ,
          0.02576596,  0.04819346],
        [-0.03260424,  0.02628894, -0.00715079,  0.02018868,
          0.01542927, -0.00427831, -0.04009442,  0.0421882 ,
          0.02576596,  0.04819346],
        [-0.03260424,  0.02628894, -0.00715079,  0.02018868,
          0.01542927, -0.00427831, -0.04009442,  0.0421882 ,
          0.02576596,  0.04819346],
        [ 0.00453651, -0.03327832,  0.00190494,  0.00053731,
         -0.00275661,  0.03503628, -0.03271526, -0.04739553,
          0.03144166, -0.03115122],
        [ 0.02055827, -0.0149114 ,  0.01584521,  0.01103797,
          0.00970151, -0.01471629, -0.04949722,  0.03224731,
         -0.04651311,  0.02156937],
        [-0.00095488, -0.02852362, -0.03390133, -0.0